import React from 'react';
import { ArrowLeft, Shield, FileText, CheckCircle, Zap, Scale, Target, History } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { cn } from '../lib/utils';

export default function Terms() {
  const navigate = useNavigate();

  const sections = [
    {
      title: '1. Account Eligibility',
      content: 'Users must be at least 18 years old to create an account. Each user is permitted only one account. Multiple accounts will result in immediate deactivation without refund.'
    },
    {
      title: '2. Earning & Withdrawals',
      content: 'Earnings are generated by viewing advertisements. Withdrawal requests are processed within 24-72 hours. Minimum withdrawal amounts apply based on your current package.'
    },
    {
      title: '3. Referral System',
      content: 'You earn bonuses for referring new users who activate a premium package. Spamming referral links or using fraudulent methods is strictly prohibited.'
    },
    {
      title: '4. Package Validity',
      content: 'Each package has a specific duration and daily ad limit. Once a package expires, you must renew or upgrade to continue earning at that rate.'
    },
    {
      title: '5. Account Security',
      content: 'You are responsible for maintaining the confidentiality of your account credentials. Ad Earn BD is not liable for any losses due to unauthorized access.'
    }
  ];

  const govImages = [
    {
      title: 'TIN Certificate',
      id: 'TIN: 747030528739',
      details: 'Registered under Taxes Circle-010, Gazipur. Issued on Sep 11, 2019.',
      description: 'Taxpayer\'s Identification Number (TIN) Certificate'
    },
    {
      title: 'Trade License',
      id: 'License No: 1147',
      details: 'Issued by Gazipur City Corporation for Travel Agency. Date: 24/03/2019.',
      description: 'Official Trade License (General)'
    }
  ];

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const item = {
    hidden: { opacity: 0, y: 10 },
    show: { opacity: 1, y: 0 }
  };

  return (
    <div className="min-h-screen bg-white pb-24 font-sans">
      <div className="bg-white/80 backdrop-blur-xl p-6 flex items-center justify-between sticky top-0 z-30">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-3 bg-gray-50 rounded-2xl hover:bg-gray-100 transition-colors">
            <ArrowLeft size={20} className="text-gray-900" />
          </button>
          <h1 className="text-xl font-black text-gray-900 tracking-tight italic uppercase">Legal Framework</h1>
        </div>
        <div className="p-3 bg-gray-50 rounded-2xl">
           <Scale size={18} className="text-gray-400" />
        </div>
      </div>

      <motion.div 
        variants={container}
        initial="hidden"
        animate="show"
        className="p-6 space-y-10"
      >
        <motion.div 
          variants={item}
          className="bg-gray-900 rounded-[40px] p-10 text-white relative overflow-hidden shadow-2xl shadow-gray-200"
        >
          <div className="absolute top-0 right-0 w-48 h-48 bg-orange-500 rounded-full blur-[80px] -mr-20 -mt-20 opacity-20"></div>
          <div className="relative z-10 space-y-6">
            <div className="flex items-center gap-3 text-orange-500">
               <Zap size={14} className="fill-orange-500" />
               <p className="text-[10px] font-black uppercase tracking-[0.3em]">Compliance Active</p>
            </div>
            <div className="space-y-2">
              <h2 className="text-3xl font-black tracking-tighter leading-none italic uppercase">Master Agreement</h2>
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest leading-relaxed">
                By initializing a session on this cluster, you synchronize with the legal protocols defined herein.
              </p>
            </div>
            <div className="flex items-center gap-2 pt-2">
               <Shield size={14} className="text-orange-500" />
               <span className="text-[10px] font-black uppercase tracking-widest text-gray-400 italic underline decoration-orange-500 underline-offset-4">Verified System Node</span>
            </div>
          </div>
        </motion.div>

        <div className="space-y-6">
          <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] px-2 flex items-center gap-2">
            <Target size={14} />
            Operating Protocols
          </h3>
          <div className="space-y-4">
            {sections.map((section, index) => (
              <motion.div 
                key={index} 
                variants={item}
                className="bg-white p-8 rounded-[40px] border border-gray-50 shadow-xl shadow-gray-100 space-y-4 lg:hover:border-orange-100 transition-all"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2.5 bg-gray-50 rounded-xl">
                    <FileText className="text-gray-900" size={16} />
                  </div>
                  <h3 className="text-sm font-black text-gray-900 tracking-tight uppercase italic">{section.title}</h3>
                </div>
                <p className="text-[11px] font-black italic text-gray-400 leading-relaxed uppercase tracking-tight">
                  {section.content}
                </p>
              </motion.div>
            ))}
          </div>
        </div>

        <motion.div variants={item} className="space-y-8 pt-4">
          <div className="flex items-center gap-3 px-2">
             <div className="w-1.5 h-6 bg-orange-600 rounded-full"></div>
             <h2 className="text-[10px] font-black text-gray-900 tracking-[0.2em] uppercase italic">Authorization Vault</h2>
          </div>
          
          <div className="bg-gray-50 rounded-[40px] p-10 space-y-10 border border-gray-100">
            <div className="space-y-2 text-center">
              <h3 className="text-sm font-black text-gray-900 uppercase tracking-tight">Official Credentials</h3>
              <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest leading-relaxed px-4">
                Operating under technical registration as <span className="text-orange-600">M/s. RAIN TOURS AND TRAVELS</span>.
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {govImages.map((img, i) => (
                <div key={i} className="space-y-4 group">
                  <p className="text-[9px] font-black text-gray-400 tracking-[0.3em] uppercase text-center">{img.title}</p>
                  <div className="relative aspect-[3/4.2] bg-white rounded-[32px] overflow-hidden border border-gray-100 shadow-2xl transition-all group-hover:scale-[1.02] active:scale-95 cursor-zoom-in">
                    <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-orange-500/0 via-orange-500 to-orange-500/0"></div>
                    <div className="w-full h-full p-8 flex flex-col items-center justify-center text-center space-y-6">
                       <div className="w-20 h-20 bg-gray-50 rounded-full flex items-center justify-center shadow-inner relative">
                          <Shield size={32} className="text-gray-300 group-hover:text-orange-500 transition-colors" />
                          <div className="absolute inset-0 bg-orange-500/10 rounded-full scale-0 group-hover:scale-100 transition-transform"></div>
                       </div>
                       <div className="space-y-1 relative z-10">
                         <p className="text-[10px] font-black text-gray-900 uppercase tracking-tight">{img.title}</p>
                         <div className="inline-block px-3 py-1 bg-orange-50 text-orange-600 rounded-lg text-[12px] font-black italic">
                           {img.id}
                         </div>
                       </div>
                       <div className="w-12 h-1 bg-gray-50 rounded-full"></div>
                       <p className="text-[9px] text-gray-400 font-extrabold leading-loose px-4 uppercase tracking-tighter italic">{img.details}</p>
                       <div className="pt-6 flex flex-col items-center space-y-2 opacity-20">
                         <History size={16} />
                         <p className="text-[8px] text-gray-400 font-black italic tracking-widest uppercase">Validated & Serialized</p>
                       </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="p-6 bg-white/50 backdrop-blur-sm rounded-[24px] border border-gray-100 italic">
               <p className="text-[9px] text-center text-gray-400 font-black uppercase tracking-widest leading-relaxed">
                * Jurisdiction: Registered Node at Monnunagar, Tongi, Gazipur-1710.
              </p>
            </div>
          </div>
        </motion.div>

        <motion.div 
          variants={item}
          className="bg-gray-900 p-10 rounded-[40px] text-center space-y-6 shadow-2xl shadow-gray-200"
        >
          <div className="w-16 h-16 bg-white/5 text-orange-500 rounded-3xl flex items-center justify-center mx-auto border border-white/5">
            <CheckCircle size={32} strokeWidth={3} />
          </div>
          <p className="text-white font-black text-sm uppercase italic tracking-tight">Full Protocol Synchronization Acknowledged</p>
          <div className="flex items-center justify-center gap-4 text-[9px] font-black text-gray-500 uppercase tracking-[0.2em]">
             <span>Ver 2.4.0</span>
             <span className="w-1 h-1 bg-gray-500 rounded-full"></span>
             <span>Ref: 2024.05.LGL</span>
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
}
